%----------------------------------------------------------------------------
--------------------
% Code to illustrate DNA quantification.
captionFontSize = 14;
% Read in a standard image
ImageName = 'Image1.png';
InfoImage = imfinfo(ImageName);
B= InfoImage.FileSize;
F= 9085414/B;
DNAImage = imread(ImageName);
%Image size standardisation
% grayscale image
DNAImage = rgb2gray(DNAImage)
% Step 1: Image check to distinguish between blank and precipitate
% The U shape border on the blank image has a threshold between 85 and 95
% when generated by the Lab on DVD player
% If the code sees the precipitate on the image then only it proceeds ahead
% to the next step. Separate threshold range for U shape border in CMOS
% sensor images.
figure
hold on
imshow(DNAImage)
DNAImage = imcrop(DNAImage)
subplot(2, 2, 1);
imshow(DNAImage);
% Maximize the figure window.
set(gcf, 'units','normalized','outerposition',[0 0 1 1]);
drawnow;
caption = sprintf('Original Image');
title(caption, 'FontSize', captionFontSize);
axis image;
% Histogram generation and display.
[pixelCount, grayLevels] = imhist(DNAImage);
%bar(grayLevels, pixelCount, 'FaceColor', 'r');
% Binary image generation, thresholdValue = 95 for DVD images
thresholdValue = 95;
binaryImg = (DNAImage < thresholdValue);
Sum2=0
for k=85:thresholdValue


 Sum2=Sum2+ pixelCount(k)*((255-grayLevels(k))/255)

end
binaryImg = imfill(binaryImg, 'holes');
% Image to concentration conversion Factor 115 determined experimentally from
% the images.For the highest concentration
% 129 ng/ul this factor gives a precipitation area of 1290 a.u. This gives
% a resolution of 1 for every 0.1ng/ul change in DNA concentration.
% This factor is separate for Camera images.
Sum= Sum2/115
subplot(2, 2, 2);
bar(pixelCount);
%title('Histogram of DNA image', 'FontSize', captionFontSize);
xlim([0 255]); % Scale x axis manually.
grid off;
% Display the threshold as a line on histogram
hold on;
maxYValue = ylim;
line([thresholdValue, thresholdValue], maxYValue, 'Color', 'b');
% Place a text label on the bar chart showing the threshold.
annotationText = sprintf('Thresholded at %d gray levels',
thresholdValue(end));
% Display the binary image.
subplot(2, 2, 3);
imshow(binaryImg);
title('Binary Image, obtained by thresholding', 'FontSize', captionFontSize);
%For blank image elimination
if (Sum2>20)
DNAImage = imadjust(DNAImage,[0.45 0.55],[]);
figure
imshow(DNAImage)
% Step 2: Second part if image is not blank
% Crop the image to keep the region containing the DNA precipitate
DNAImage = imcrop(DNAImage)
% Display the grayscale image.
% Image adjustment: it works for most images from the DVD. This contrast step
% makes the DNA look prominent over its background which is necessary for its
% quantification.
subplot(2, 2, 1);
imshow(DNAImage);
% Maximize the figure window.
set(gcf, 'units','normalized','outerposition',[0 0 1 1]);
drawnow;
caption = sprintf('Original Image');
title(caption, 'FontSize', captionFontSize);
axis image;
% Histogram generation and display.
[pixelCount, grayLevels] = imhist(DNAImage);
% Binary image generation
s=nonzeros(pixelCount)
A=max(s)
Y = quantile(s,[0,0.8])
thresholdValue = find(pixelCount>Y(2),1);
binaryImg = (DNAImage < thresholdValue);
Sum2=0
for k=1:thresholdValue+10

 Sum2=Sum2+ pixelCount(k)*((255-grayLevels(k))/255)

end
binaryImg = imfill(binaryImg, 'holes');
% Factor 115 (Multiply F by suitable value for Camera images) below is to
%ensure 129 ng/ul in 10 ul volume, this factor gives a precipitation area of
%1290 a.u. This gives a resolution of 1 for every 0.1ng/ul change in DNA
%concentration. So, in essence the value of the precipitation level by
%adjusting F should be fixed as the product of known concentration and
%volume of sample.
%Sum= (Sum2*(F)/115)/10.46 +14
%Calculating unknown quantity of DNA
Sum= Sum2*F/115
%Calculating precipitation level
subplot(2, 2, 2);
bar(pixelCount);
%title('Histogram of DNA image', 'FontSize', captionFontSize);
xlim([0 20]); % Scale x axis manually.
ylim([0 1800])
grid off;
% Display the threshold as a line on histogram
hold on;
maxYValue = ylim;
line([thresholdValue, thresholdValue], maxYValue, 'Color', 'b');
% Place a text label on the bar chart showing the threshold.
annotationText = sprintf('Thresholded at %d gray levels',
thresholdValue(end));
% Display the binary image.
subplot(2, 2, 3);
imshow(binaryImg);
title('Binary Image, obtained by thresholding', 'FontSize', captionFontSize);
subplot(2, 2, 4);
imshow(DNAImage);
title('Outlines, from bwboundaries()', 'FontSize', captionFontSize);
axis image;
hold on;
end
